import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unusedImports from "eslint-plugin-unused-imports";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/types/database.ts", // auto-generated by Supabase CLI
    "src/components/ui/**", // auto-generated by shadcn CLI
  ]),
  {
    plugins: {
      "simple-import-sort": simpleImportSort,
      "unused-imports": unusedImports,
    },
    rules: {
      // Import ordering
      "simple-import-sort/imports": [
        "error",
        {
          groups: [
            // 1. React and Next.js
            ["^react", "^next"],
            // 2. Third-party packages
            ["^@?\\w"],
            // 3. Internal ~/  aliases
            ["^~/"],
            // 4. Relative imports
            ["^\\."],
            // 5. Side-effect imports
            ["^\\u0000"],
            // 6. CSS / style imports
            ["\\.css$"],
          ],
        },
      ],
      "simple-import-sort/exports": "error",

      // Unused imports
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
      // Disable the base rule — unused-imports handles it
      "@typescript-eslint/no-unused-vars": "off",

      // No duplicate imports
      "no-duplicate-imports": "error",
    },
  },
]);

export default eslintConfig;
